/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cumples;

import java.io.BufferedReader;
import java.io.FileReader;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Roland
 */
public class Cumples extends javax.swing.JFrame {

    /**
     * Creates new form Cumples
     */
    JOptionPane alerta = new JOptionPane();
    
    public Cumples() {
        initComponents();

        try {
            FileReader fr = new FileReader("./cumples.txt");
            BufferedReader br = new BufferedReader(fr);
            Date fecha = new Date();// fecha actual
            int hoy = fecha.getDate();
            int mes_actual = fecha.getMonth() + 1;
            String cadenaFecha = hoy + "/" + mes_actual;//fecha actual formato del fichero dd/mm
            String ffecha = ""; //fechas guardadas en el fichero
            String Linea = "";
            String Cumpleanos_hoy = "<html>";
            while ((Linea = br.readLine()) != null) {

                String[] x = Linea.split("\\|");
                ffecha = x[1]; // asigno la fecha

                if (ffecha.equals(cadenaFecha)) {
                    //hay coincidencia de cumple.
                    
                    Cumpleanos_hoy += x[0]+":  "+x[1] + "<br/>";
                    
                    System.out.println(Cumpleanos_hoy);

                }
            }
            Cumpleanos_hoy+="</html>";
            ImprimirCumples.setText(Cumpleanos_hoy);

        } catch (Exception ex) {
            
            alerta.showMessageDialog(null,"Error de apertura de fichero o en su lectura"+ex);
            System.out.println("Error de apertura de fichero o en su lectura: " + ex);
            //Logger.getLogger(Cumples.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        ImprimirCumples = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cumples/fondo.jpg"))); // NOI18N
        jLabel1.setAlignmentY(0.0F);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cumpleaños Hoy");
        setLocation(new java.awt.Point(320, 320));
        setMaximumSize(new java.awt.Dimension(500, 500));
        setMinimumSize(new java.awt.Dimension(449, 300));
        setPreferredSize(new java.awt.Dimension(449, 321));
        setResizable(false);
        setSize(new java.awt.Dimension(449, 321));
        getContentPane().setLayout(null);

        ImprimirCumples.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        ImprimirCumples.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(ImprimirCumples);
        ImprimirCumples.setBounds(60, 70, 240, 140);

        jButton2.setText("Nuevo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(60, 233, 63, 30);

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cumpleaños Hoy");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 24, 150, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cumples/fondo.jpg"))); // NOI18N
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 450, 300);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        JPanel x = new Nuevo();
        JFrame f = new JFrame();
        f.getContentPane().add(x);
        f.setSize(500, 300);
        f.setLocation(getWidth() / 2, getHeight() / 2);
        f.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cumples.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cumples.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cumples.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cumples.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cumples().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ImprimirCumples;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
